---
- import_tasks: setup.yml
  tags: 
    - nodejs

- name: Define nodejs_install_npm_user.
  set_fact:
    nodejs_install_npm_user: "{{ system_user }}"
  when: nodejs_install_npm_user is not defined
  tags:
    - nodejs

- name: Create npm global directory.
  file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_npm_user }}"
    group: "{{ nodejs_install_npm_user }}"
    state: directory
    mode: 0755
  become: true
  tags:
    - nodejs

- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644
  become: true
  tags:
    - nodejs

- import_tasks: pm2.yml
  tags: 
    - nodejs
    - pm2
